version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - 8000:80
      - 5173:5173
    expose:
      - "9000"
      - "9003"
    environment:
      APP_ENV: dev
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-client_host=host.docker.internal}
      PHP_IDE_CONFIG: "serverName=Backend"
    volumes:
      - ./html:/var/www/html
      - ./ssh:/var/www/.ssh
    container_name: test_sf_web
  database:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testSf
    volumes:
      - mysql-data3:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: test_sf_db


volumes:
  mysql-data3: null

